version: "3.4"

services:
  order-service:
    environment:
      - ASPNETCORE_URLS=http://+:5126
      - ConnectionStrings__MongoDB=mongodb://root:root@mongo:27017
      - ConnectionStrings__RabbitMQ=amqp://admin:admin@rabbitmq:5672
    ports:
      - "5126:5126"
  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "15692:15692"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  mongo:
    image: mongo
    hostname: mongo
    environment: 
        - MONGO_INITDB_DATABASE=test
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
    volumes: 
        - mongodata:/data/db
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports: 
        - 27017-27019:27017-27019
volumes:
  mongodata:
  rabbitmqdata:
